name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # - mlflow=2.8.1
  - hydra-core=1.3.2
  - matplotlib=3.7.3 # =3.8.2 : otherwise error with pandas-profiling
  - pandas=1.4.2
  - pip=23.3.1
  - pydantic=1.  # added pydantic
  #- scikit-learn=1.3.2  # conflict with pandas-profiling=3.1.0
  - jupyterlab=4.1.3
  #- pydantic=2.6  # added to prevent pydantic error
  - ipywidgets
  - pandas-profiling=3.1.0  # added pandas-profiling --> error due to pydantic
  #- pandas=2.1.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0

