name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.7.3  # matching eda/conda.yml; original was 3.8.2
  - pandas=1.4.2
  - pip=23.3.1
  - pydantic=1.  # added pydantic
  - jupyterlab=4.1.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
